name: melissafuller
favicon: null
layout_spectrum: 0.6280564309563488
typography_spectrum: 0.7767972513101995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7764272652566433
  lightness: 0.9394457400776446
  saturation: 0.2783254391979426
  rhythmicContrast: 0.373691663146019
purpose: []
